disable-version-check: false
log-level: info
report:
    fail-on-severity: critical,high,medium,low
    format: json
    no-color: false
    output: ""
    report: security
    severity: critical,high,medium,low,warning
rule:
    disable-default-rules: false
    only-rule: []
    skip-rule: []
scan:
    context: ""
    data_subject_mapping: ""
    disable-domain-resolution: true
    domain-resolution-timeout: 3s
    external-rule-dir: []
    force: false
    hide_progress_bar: false
    internal-domains: []
    parallel: 0
    quiet: true
    scanner:
        - secrets
    skip-test: true
